---
- hosts: nodes
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:
    - name: ensure curl is installed
      apt:
        update_cache: yes
        name: curl
        state: present

    - name: create a demo file
      file:
        path: /home/ansible/demo.txt
        state: touch
        owner: ansible

- hosts: node[1:4]
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:
    - name: install etcd
      apt:
        update_cache: yes
        name: etcd
        state: present

- hosts: node5
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:
    - name: install nginx
      apt:
        update_cache: yes
        name: nginx
        state: present